### ISSUE TITLE
check_shutdown - control file broken; systemd support?

### ISSUE THREAD

**Issue by bzed** [bzed/pkg-nagios-plugins-contrib#54]
@petterreinholdtsen - check_shutdown has a broken control file + I think it won't work with systemd. Please fix it.

**Comment by waja** [comment]
That's the problem of let everybody dump stuff anywhere and hope other ppl are caring afterwards. Same happened to monitoring-plugins in the past and the did throw them away cause they where horribly outdated and broken.
@petterreinholdtsen are you still caring about check_shutdown or should we remove it from the package?

**Comment by petterreinholdtsen** [comment]
I assumed more information would show up, as "is broken" and "I think it won't work with systemd" was so vague it is impossible for me to know what the problem is.  How does the brokenness materialize?  What causes it to not work with systemd?

**Comment by bzed** [comment]
@petterreinholdtsen with a script of about 5 lines of useful code, and one actually used to detect a shutdown, what do you think what might not work with systemd? Run shutdown 2000 on testing/unstable and see if your line of code will produce some output.
