### ISSUE TITLE
plugin is not working

### ISSUE THREAD

**Issue by wojtas911** [bzed/pkg-nagios-plugins-contrib#58]
Hi,
/usr/lib64/nagios/plugins/pmp-check-aws-rds.py -l
List of all DB instances:
[]
that all i get, it's probably new aws cli

**Comment by waja** [comment]
As this project is only about packaging this plugin into a Debian package, if would be very useful if you can report your Problem upstream at  https://github.com/percona/percona-monitoring-plugins/issues/

**Comment by waja** [comment]
Closing this, as ist would be more reasonable to report it upstream. Maybe it's fixed there already.
