### ISSUE TITLE
check_raid: v4.0.3 release

### ISSUE THREAD

**Issue by waja** [bzed/pkg-nagios-plugins-contrib#65]
Please update to 4.0.3 (https://github.com/glensc/nagios-plugin-check_raid/blob/4.0.3/ChangeLog.md)

**Comment by waja** [comment]
https://github.com/glensc/nagios-plugin-check_raid/blob/4.0.3/bin/check_raid.pl seems not the fat perl script (anymore)

**Comment by bzed** [comment]
its a perl library and a script now, but that should not really make a difference. Might need a bit of perl makefile.PL or something like that, though.

**Comment by waja** [comment]
I've an update in the pipeline. :)

**Comment by waja** [comment]
Fixed by a316cb86a5eef7f850d85af68d5765f4431f6476
