### ISSUE TITLE
travis-ci: Please fix autopkgtest

### ISSUE THREAD

**Issue by waja** [bzed/pkg-nagios-plugins-contrib#66]
https://travis-ci.org/bzed/pkg-nagios-plugins-contrib/jobs/180384889#L3899-L3907

**Comment by evgeni** [comment]
on it

fixed:
* not properly started httpd during tests
* new output of apache2 status page
* travis.d.n problems when using stable instead of jessie

open:
* bad test dependencies on stable

**Comment by evgeni** [comment]
done in 3478a485f8be996ac0f772c36fd8fd696cd430f9
