### ISSUE TITLE
Argument "6 hours 28 minutes 17 seconds" isn't numeric in subtraction

### ISSUE THREAD

**Issue by pkhadka56** [bzed/pkg-nagios-plugins-contrib#82]
# ./check_httpd_status -H localhost

Argument "6 hours 28 minutes 17 seconds" isn't numeric in subtraction (-) at ./check_httpd_status line 322.
HTTPD_STATUS OK - 1.294 s - 1/5 Busy/Idle, 144/150 Open/Total, 0.0 requests/s, 0.0 B/s, 0 B/request | ReqPerSec=0.000req/s;; BytesPerSec=0.00B/s;; OpenSLot=144;; Closing=0;; DNS=0;; Finishing=0;; Idle=0;; Keepalive=0;; Logging=0;; Reading=0;; Starting=0;; Sending=1;; Waiting=5;; FreeWorker=149;;;0;

**Comment by evgeni** [comment]
This should be fixed by https://github.com/bzed/pkg-nagios-plugins-contrib/blob/master/debian/patches/check_httpd_status/numeric-uptime. Are you running the unpatched version?

**Comment by pkhadka56** [comment]
seems to be patched but not working. I find below code in file:

239 my $Uptime = 0;
240 if ( $webcontent =~ m/Uptime: (.*?)\n/) {
241         $Uptime = $1;
242         $patternFound++;
243 }

**Comment by evgeni** [comment]
I'd say that is not patched? It would've been \d in the patched version. How did you build the package?

**Comment by pkhadka56** [comment]
Oh Yes, I didn't noticed it. I have changed the code but still saw same error. This time I see one line error.

I am directly using from below:

https://raw.githubusercontent.com/bzed/pkg-nagios-plugins-contrib/master/check_httpd_status/check_httpd_status

**Comment by pkhadka56** [comment]
Seems like working. Thanks.
